src/objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Rent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Rent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cars</relationshipLabel>
        <relationshipName>Cars_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Type</label>
        <referenceTo>Car_Type__c</referenceTo>
        <relationshipLabel>Cars</relationshipLabel>
        <relationshipName>Cars</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CarSearchController.cls
public with sharing class CarSearchController {
    @AuraEnabled
    public static List<Car__c> getCars(string carCategoryTypeId){ 
        system.debug('carCategoryTypeId ' + carCategoryTypeId);
        List<Car__c> cars;
     
        //PMD plugin foce to check access of the user
        if((carCategoryTypeId == null ||   string.isEmpty(carCategoryTypeId))  && Contact.getSObjectType().getDescribe().isAccessible()){ 
            cars = [SELECT Id, Name, Picture__c, Contact__r.Name, Geolocation__latitude__s,Geolocation__longitude__s from Car__c WHERE Available_For_Rent__c = true];

        }else { 
            if(Contact.getSObjectType().getDescribe().isAccessible()){
                cars = [SELECT Id,Name,Picture__c, Contact__r.Name, Geolocation__latitude__s, Geolocation__longitude__s from Car__c WHERE Type__c = :carCategoryTypeId AND Available_For_Rent__c = true];
        }
    }
     
        return cars;
    }
 }